<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="WolverineFx.Http" Version="6.2.2" />
        <PackageReference Include="WolverineFx.RabbitMQ" Version="6.2.2" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\DisJockey.Shared\DisJockey.Shared.csproj" />
    </ItemGroup>

    <ItemGroup Condition="'$(Configuration)' == 'Debug'">
        <PackageReference Include="WolverineFx.RuntimeCompilation" Version="6.2.2" />
    </ItemGroup>

</Project>
