version: '3.4'

services:
  disjockey.api:
    container_name: disjockey.api
    image: ${DOCKER_REGISTRY-}disjockey
    build:
      context: .
      dockerfile: DisJockey/Dockerfile
    networks:
      - disjockey-network

networks:
  disjockey-network:
    driver: bridge