version: '3.4'

services:
  disjockey.api:
    container_name: disjockey.api
    image: ${DOCKER_REGISTRY-}disjockey
    build:
      context: .
      dockerfile: DisJockey/Dockerfile.local
    volumes:
      - ./DisJockey/wwwroot:/app/wwwroot
      - ./DisJockey/appsettings.json:/app/appsettings.json
    networks:
      - disjockey-network

  disjockey.botservice:
    container_name: disjockey.botservice
    image: ${DOCKER_REGISTRY-}disjockeybotservice
    build:
      context: .
      dockerfile: DisJockey.BotService/Dockerfile
    volumes:
      - ./DisJockey.BotService/appsettings.json:/app/appsettings.json
    networks:
      - disjockey-network

  lavalink:
    container_name: lavalink
    image: ghcr.io/lavalink-devs/lavalink:4.0.6 # pin the image version to Lavalink v4
    restart: unless-stopped
    environment:
      - _JAVA_OPTIONS=-Xmx6G # set Java options here
      - SERVER_PORT=2333 # set lavalink server port
    volumes:
      - ./application.yml:/opt/Lavalink/application.yml
    networks:
      - disjockey-network

networks:
  disjockey-network:
    driver: bridge