<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>dotnet-DisJockey.BotService-a3689998-f780-45c8-b18a-a4564dd36936</UserSecretsId>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Discord.Net" Version="3.19.1" />
        <PackageReference Include="Grpc.AspNetCore" Version="2.67.0" />
        <PackageReference Include="Lavalink4NET.Discord.NET" Version="4.2.1" />
        <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="10.0.7" />
        <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\DisJockey.Messaging\DisJockey.Messaging.csproj" />
        <ProjectReference Include="..\DisJockey.ServiceDefaults\DisJockey.ServiceDefaults.csproj" />
        <ProjectReference Include="..\DisJockey.Shared\DisJockey.Shared.csproj" />
    </ItemGroup>
</Project>
