<Project Sdk="Microsoft.NET.Sdk.Worker">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>dotnet-DisJockey.BotService-a3689998-f780-45c8-b18a-a4564dd36936</UserSecretsId>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Discord.Net" Version="3.18.0" />
        <PackageReference Include="Lavalink4NET.Discord.NET" Version="4.1.0" />
        <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="10.0.1" />
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.1" />
        <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.22.1" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\DisJockey.Messaging\DisJockey.Messaging.csproj" />
        <ProjectReference Include="..\DisJockey.ServiceDefaults\DisJockey.ServiceDefaults.csproj" />
    </ItemGroup>
</Project>
