<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Grpc.Net.ClientFactory" Version="2.80.0" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\DisJockey.Core\DisJockey.Core.csproj" />
        <ProjectReference Include="..\DisJockey.Shared\DisJockey.Shared.csproj" />
    </ItemGroup>

</Project>
