name: Angular

on: 
  push:
    branches: 
      - main
      
jobs:
  build:

    runs-on: ubuntu-latest

    env:
      working-directory: ./client

    steps:
    - uses: actions/checkout@v2.3.2

    - name: Use Node.js 14 LTS
      uses: actions/setup-node@v2
      with:
        node-version: '14'
      
    - name: Install NPM Modules
      run: npm install
      working-directory: ${{env.working-directory}}

    - name: Build Project
      run: npm run build-prod
      working-directory: ${{env.working-directory}}