name: Build DisJockey

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-api:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore

  
  build-angular:

    runs-on: ubuntu-latest

    env:
      working-directory: ./DisJockey/ClientApp

    steps:
    - uses: actions/checkout@v2.3.2

    - name: Use Node.js 14 LTS
      uses: actions/setup-node@v2
      with:
        node-version: '14'
      
    - name: Install NPM Modules
      run: npm install
      working-directory: ${{env.working-directory}}

    - name: Build Project
      run: npm run build-prod
      working-directory: ${{env.working-directory}}
