# Docs for the Azure Web Apps Deploy action: https://go.microsoft.com/fwlink/?linkid=2134798
# More GitHub Actions for Azure: https://go.microsoft.com/fwlink/?linkid=2135048

name: Azure App Service - disjockey(Production), Build and deploy DotnetCore app

on:
  push:
    branches:
      - master

jobs:
  build-api:
    runs-on: windows-latest

    steps:
    # checkout the repo
    - name: 'Checkout Github Action'
      uses: actions/checkout@master


    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build with dotnet
      run: dotnet build --no-restore

    - name: dotnet publish
      run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp

  build-angular:

    runs-on: windows-latest

    env:
      working-directory: ./client

    steps:
    - uses: actions/checkout@v2.3.2

    - name: Use Node.js 14 LTS
      uses: actions/setup-node@v2
      with:
        node-version: '14'
      
    - name: Install NPM Modules
      run: npm install
      working-directory: ${{env.working-directory}}

    - name: Build Project
      run: npm run build-prod
      working-directory: ${{env.working-directory}}

  deploy:

    runs-on: windows-latest

    steps:

      - name: Run Azure webapp deploy action using publish profile credentials
        uses: azure/webapps-deploy@v2
        with:
          app-name: disjockey
          slot-name: Production
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_3ECCAA35A552408D85B2F5C2A2945220 }}
          package: ${{env.DOTNET_ROOT}}/myapp

