syntax = "proto3";

import "google/protobuf/empty.proto";

option csharp_namespace = "DisJockey.Shared.Protos";

package disjockey;

service DisJockeyGrpc {
	rpc GetUserVoiceChannel (GetUserVoiceChannelRequest) returns (GetUserVoiceChannelResponse);
	rpc GetTrackStatus (GetTrackStatusRequest) returns (GetTrackStatusResponse);
	rpc PlayPauseTrack (PlayPauseTrackRequest) returns (google.protobuf.Empty);
}

message GetUserVoiceChannelRequest {
	uint64 user_id = 1;
}

message GetUserVoiceChannelResponse {
	string voiceChannelName = 1;
	uint64 voiceChannelId = 2;
	string serverName = 3;
	uint64 serverId = 4;
}

message GetTrackStatusRequest {
	uint64 server_id = 1;
	uint64 voice_channel_id = 2;
}

message GetTrackStatusResponse {
	string track_id = 1;
	string track_name = 2;
	bool paused = 3;
}

message PlayPauseTrackRequest {
	uint64 server_id = 1;
	uint64 voice_channel_id = 2;
}